### ISSUE TITLE
Are prebuilt bitstream and image available? 

### ISSUE THREAD

**Issue by xu-jiachen** [slaclab/Simple-rfsoc-4x2-Example#1]
Thank you for making this repo available. I wonder if you could share prebuilt bitstream and image for us to try.

**Comment by ruck314** [comment]
@xu-jiachen The pre-built images are tar.gz into a single file in the tag release:
https://github.com/slaclab/Simple-rfsoc-4x2-Example/releases/tag/v1.7.0
![image](https://github.com/user-attachments/assets/06b4a1fb-c445-4463-9f2d-d51922b23924)

```bash
$ tar zxvf SimpleRfSoc4x2Example-0x01070000-20240705115515-ruckman-c308de9.petalinux.tar.gz
linux/system.bit
linux/BOOT.BIN
linux/image.ub
linux/boot.scr
$ ll linux/
total 133672
-rw-r--r-- 1 ruckman re 36181008 Jul  5 12:30 BOOT.BIN
-rw-r--r-- 1 ruckman re     3476 Jul  5 12:17 boot.scr
-rw-r--r-- 1 ruckman re 66250096 Jul  5 12:30 image.ub
-rw-r--r-- 1 ruckman re 34437483 Jul  5 12:11 system.bit
```
